# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 19:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=52)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(b'^[0-9]*$', b'Only numbers are allowed.'), django.core.validators.MinLengthValidator(10, b'It can only be 10 decimals')])),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
